version: "3"

services:
  galactus:
    container_name: galactus
    build: .
    ports:
      - 5000
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: [gpu]
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - galactus
    
