version: "3"

# define services
services:
  api:
    # define container name
    container_name: galactus
    # point to dockerfile for api build
    build: .
    # define ports to expose
    ports:
        - "${API_PORT}:${API_PORT}"
    networks:
      customnetwork:
        ipv4_address: ${FLASK_IP}
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: [gpu]
  webserver:
    image: nginx
    container_name: web-server
    networks:
      customnetwork:
        ipv4_address: ${NGINX_IP}

networks:
  customnetwork:
    ipam:
      config:
        - subnet: ${SUBNET}